id: '17267525560280.06514076986327177'
definitionId: frameDrawer
parentSlotId: '2'
styles:
  xl:
    gridItem:
      x: 3
      y: 490
      w: 3
      h: 9
    flex:
      size:
        widthValue: auto
        heightValue: 36
        heightUnit: px
      grow: '0'
      shrink: '0'
    backgroundColor:
      value: default
      dataValue: default
      withData: false
    status:
      value: default
      dataValue: default
      withData: false
    buttonIconPlacement: left
  xs:
    gridItem:
      x: 0
      y: 289
      w: 24
      h: 9
    flex:
      size:
        widthValue: auto
        heightValue: 36
        heightUnit: px
      grow: '0'
      shrink: '0'
properties:
  name: frameDrawer_config
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  buttonText: config
  buttonHidden:
    value: true
    dataValue: 'false'
    withData: false
  buttonStatus:
    value: primary
    dataValue: primary
    withData: false
  buttonIcon:
    value: alert-triangle
    dataValue: star-outline
    withData: false
  closeOnBackdrop: false
  closeOnEsc: false
actions:
  init:
    - action: '17267675634220.9091299089134555'
      paramCode: ''
      blockPageLoad: false
      preventDefault: false
      index: 0
  open: []
  close: []
slots:
  - id: '17267525560280.3202073794842475'
    name: header
    children:
      - heading4.yml
  - id: '17267525560280.4533345403482849'
    name: body
    children:
      - card5/card5.yml
      - card6/card6.yml
      - card7/card7.yml
      - icon2.yml
      - text9.yml
      - icon3.yml
      - text10.yml
      - card15/card15.yml
  - id: '17267525560280.025277106329494536'
    name: footer
    children: []
